---
title: "Data Exploration- Childs"
author: "Simon Marks"
date: "12/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## Childs Soil Moisture Data (Nov. 2020 compile)

```{r}

Childs_SM_Nov2020 <- readr::read_csv("Childs_SM_Nov2020/compiled_Childs_Nov2020.csv", 
                                 col_types = cols(Date = col_character(), .default = col_double())) %>% 
  dplyr::mutate(Date = as.POSIXct(Date, tz = "UTC"))

# filter out bad data, same technique for what was compiled into weekly averages
Childs_SM_good_data_Nov2020 <- Childs_SM_Nov2020 %>%
  dplyr::mutate(dplyr::across(starts_with("VWC"), ~ case_when(
    . <= 0 | . > 1 ~ NA_real_,
    TRUE ~ .
  )))

```

### CHILDST2

```{r}

# data for plotting
CHILDST2 <- Childs_SM_good_data_Nov2020 %>% 
  dplyr::select(Date, ends_with("CHILDST2")) %>% 
  # oldest data in this comp is 2019-07-11 11:00:00
  dplyr::filter(Date >= as.POSIXct("2019-07-11 11:00:00", tz = "UTC")) %>%
  tidyr::pivot_longer(cols = ends_with("CHILDST2"), names_to = "Sensor Depth", values_to = "VWC")

# time series ggplot for CHILDST2
CHILDST2_timeseries <- CHILDST2 %>%
  mutate(`Sensor Depth` = as.factor(`Sensor Depth`)) %>%
  dplyr::filter(Date >= as.POSIXct("2019-07-11 11:00:00", tz = "UTC") & Date <= as.POSIXct("2020-11-23 12:00:00", tz = "UTC")) %>% 
  # avoid problem of inconsistent time series
  filter(!is.na(VWC)) %>% 
  ggplot(aes(x = Date, y = VWC)) +
  geom_line(aes(color = `Sensor Depth`), size = 1) +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "4 months")

CHILDST2_timeseries

```

### CHILDST3

Notes:

* 60 cm depth is erratic

```{r}

# data for plotting
CHILDST3 <- Childs_SM_good_data_Nov2020 %>% 
  dplyr::select(Date, ends_with("CHILDST3")) %>% 
  # oldest data in this comp is 2019-07-08 13:30:00
  dplyr::filter(Date >= as.POSIXct("2019-07-08 13:30:00", tz = "UTC")) %>%
  tidyr::pivot_longer(cols = ends_with("CHILDST3"), names_to = "Sensor Depth", values_to = "VWC")

# time series ggplot for CHILDST3
CHILDST3_timeseries <- CHILDST3 %>%
  mutate(`Sensor Depth` = as.factor(`Sensor Depth`)) %>%
  dplyr::filter(Date >= as.POSIXct("2019-07-08 13:30:00", tz = "UTC") & Date <= as.POSIXct("2020-11-23 12:00:00", tz = "UTC")) %>% 
  # avoid problem of inconsistent time series
  filter(!is.na(VWC)) %>% 
  ggplot(aes(x = Date, y = VWC)) +
  geom_line(aes(color = `Sensor Depth`), size = 1) +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "4 months")

CHILDST3_timeseries

```