---
title: "Data Exploration- RC"
author: "Simon Marks"
date: "8/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## RC Soil Moisture Data (July 2020 compile)

```{r}

# Rock Creek
RC_SM <- readr::read_csv("RC_SM_July2020/compiled_RC_July2020_plusJJdata.csv", 
                         col_types = cols(Date = col_character(), .default = col_double())) %>% 
  dplyr::mutate(Date = as.POSIXct(Date, tz = "UTC"))

```

## RC Soil Moisture Data (Aug 2020 compile)

```{r}
RC_SM_Aug2020 <- readr::read_csv("RC_SM_Aug2020/compiled_RC_Aug2020.csv", 
                                 col_types = cols(Date = col_character(), .default = col_double())) %>% 
  dplyr::mutate(Date = as.POSIXct(Date, tz = "UTC"))
```

### RCSM2

Notes: 100 cm is no good, must be a air gap, 75 cm is consistently very low VWC, data seems to be best for (20, 30, 50, 60 cm depths)

```{r}

RCSM2 <- RC_SM_Aug2020 %>% 
  dplyr::select(Date, ends_with("RCSM2")) %>% 
  dplyr::filter(Date > as.POSIXct("2019-09-03 15:00:00", tz = "UTC")) %>%
  # dplyr::mutate(dplyr::across(starts_with("VWC"), ~ .x + 0.12)) %>% 
  tidyr::pivot_longer(cols = ends_with("RCSM2"), names_to = "Sensor Depth", values_to = "VWC")

RCSM2_timeseries <- RCSM2 %>% 
  mutate(`Sensor Depth` = as.factor(`Sensor Depth`)) %>% 
  dplyr::filter(`Sensor Depth` != "VWC_100cm_RCSM2") %>%
  ggplot(aes(x = Date, y = VWC)) + 
  geom_line() + 
  facet_wrap(~`Sensor Depth`, ncol = 2) +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "3 month")



RCSM2_timeseries <- RCSM2 %>%
  mutate(`Sensor Depth` = as.factor(`Sensor Depth`)) %>%
  dplyr::filter(`Sensor Depth` %in% c("VWC_50cm_RCSM2")) %>%
  dplyr::filter(Date > as.POSIXct("2020-7-7 00:00:00", tz = "UTC") & Date < as.POSIXct("2020-7-9 00:00:00", tz = "UTC")) %>% 
  ggplot(aes(x = Date, y = VWC)) +
  geom_line(aes(color = `Sensor Depth`), size = 1) +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "1 day")

RCSM2_timeseries

```

John's Data

```{r}
RCSM2_John <- RC_SM %>% 
  dplyr::select(Date, ends_with("RCSM2_JJ")) %>% 
  dplyr::filter(Date > as.POSIXct("2019-07-19 16:30:00", tz = "UTC")) %>% 
  tidyr::pivot_longer(cols = ends_with("RCSM2_JJ"), names_to = "Sensor Depth", values_to = "VWC")

RCSM2_John_timeseries <- RCSM2_John %>% 
  # dplyr::filter(Date > as.POSIXct("2020-5-26 00:00:00", tz = "UTC") & Date < as.POSIXct("2020-5-28 00:00:00", tz = "UTC")) %>%
  ggplot(aes(x = Date, y = VWC)) +
  geom_line(aes(color = `Sensor Depth`), size = 1) +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "3 month")

RCSM2_John_timeseries

```

## RCSM3

Notes: 75 cm is no good, due to collapsing of the hole (conferred with Campbell Sci)
100 cm is saturated
Spikes over 0.6 VWC?

```{r}

RCSM3 <- RC_SM_Aug2020 %>% 
  dplyr::select(Date, ends_with("RCSM3")) %>% 
  dplyr::filter(Date > as.POSIXct("2019-12-14 13:00:00", tz = "UTC")) %>%
  tidyr::pivot_longer(cols = ends_with("RCSM3"), names_to = "Sensor Depth", values_to = "VWC")

RCSM3_timeseries <- RCSM3 %>% 
  dplyr::filter(`Sensor Depth` != "VWC_75cm_RCSM3") %>% 
  # dplyr::filter(Date > as.POSIXct("2020-7-20 00:00:00", tz = "UTC") & Date < as.POSIXct("2020-7-25 00:00:00", tz = "UTC")) %>% 
  ggplot(aes(x = Date, y = VWC)) + 
  geom_line(aes(color = `Sensor Depth`), size = 1) +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "2 month")

RCSM3_timeseries

```

## RCSM1

Notes: 1 meter depth sensor was having problems, 

```{r}

RC1SM <- RC_SM_Aug2020 %>% 
  dplyr::select(Date, ends_with("RC1SM")) %>%
  tidyr::pivot_longer(cols = ends_with("RC1SM"), names_to = "Sensor Depth", values_to = "VWC") %>% 
  mutate(VWC = case_when(
    VWC < 0 ~ NA_real_,
    TRUE ~ VWC
  ))


RC1SM_timeseries <- RC1SM %>% 
  ggplot(aes(x = Date, y = VWC)) + 
  geom_line(aes(color = `Sensor Depth`), size = 1) +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "3 month")

RC1SM_timeseries
```


# RCSM5

```{r}

RCSM5 <- RC_SM_Aug2020 %>% 
  dplyr::select(Date, ends_with("RCSM5")) %>%
  tidyr::pivot_longer(cols = ends_with("RCSM5"), names_to = "Sensor Depth", values_to = "VWC")

RCSM5_timeseries <- RCSM5 %>% 
  ggplot(aes(x = Date, y = VWC)) + 
  geom_line(aes(color = `Sensor Depth`), size = 1) +
  scale_x_datetime(date_labels = "%Y %b %d", date_breaks = "2 month")

RCSM5_timeseries

```



